<?php
declare(strict_types = 1);

use Edifference\In3OnsiteMessaging\Block\ProductBanner;
/** @var ProductBanner $block */
?>
<div id="in3" data-bind="scope: 'product'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#in3": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "product": {
                        "component": "Edifference_In3OnsiteMessaging/js/product",
                        "config": {
                            "min":"<?= $block->getMin(); ?>",
                            "max": "<?= $block->getMax(); ?>"
                        }
                    }
                }
            }
        }
    }
</script>
