<?php
declare(strict_types = 1);

use Edifference\In3OnsiteMessaging\Block\CartBanner;
/** @var CartBanner $block */
?>
<div id="in3" data-bind="scope: 'cart'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#in3": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "cart": {
                        "component": "Edifference_In3OnsiteMessaging/js/cart",
                        "config": {
                            "min":"<?= $block->getMin(); ?>",
                            "max": "<?= $block->getMax(); ?>"
                        }
                    }
                }
            }
        }
    }
</script>
