<?php
declare(strict_types = 1);

use Edifference\In3OnsiteMessaging\Block\ProductBanner;

/**
 * @var ProductBanner $block
 */
?>
<div id="in3" data-bind="scope: 'in3-product-banner'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#in3": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "in3-product-banner": {
                        "component": "Edifference_In3OnsiteMessaging/js/in3-banner/product",
                        "config": {
                            "min":"<?= $block->escapeJs($this->getMin()); ?>",
                            "max": "<?= $block->escapeJs($this->getMax()); ?>",
                            "theme": "<?= $block->escapeJs($this->getTheme()); ?>",
                            "url": "<?= $block->escapeJs($this->getPayIn3Url()); ?>"
                        }
                    }
                }
            }
        }
    }
</script>
